exampleData = [('www.nofluffjobs.com/pl/job/junior-software-engineer-bytedance-tiktok-warszawa-xhmhuwux', 'backend'),
               ('www.nofluffjobs.com/pl/job/react-native-expert-software-mansion-krakow-nuvvhrha', 'mobile'),
               ('www.nofluffjobs.com/pl/job/senior-product-designer-netguru-remote-ugtzerdy', 'ux'),
               ('www.nofluffjobs.com/pl/job/administrator-systemu-devire-poznan-uyniuexc', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/big-data-python-developer-onwelo-remote-mf9tcm95', 'big-data'),
               ('www.nofluffjobs.com/pl/job/android-developer-untitled-kingdom-krakow-xotwrd1i', 'mobile'), (
               'www.nofluffjobs.com/pl/job/it-project-manager-it-tech-lead-prodata-consult-warsaw-kw8gimb3',
               'project-manager'),
               ('www.nofluffjobs.com/pl/job/project-manager-prodata-consult-warszawa-yfle6aly', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/senior-frontend-developer-react-codibly-remote-bihble1b', 'frontend'), (
               'www.nofluffjobs.com/pl/job/administrator-systemow-informatycznych-aplikacje-krytyczne-warszawa-wru5o6a1',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-prodata-consult-warszawa-ewtej0eg', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/endpoint-manager-avenga-wroclaw-ntboyc0m', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/cloud-specialist-wipro-digital-cracow-fbax2xye', 'big-data'),
               ('www.nofluffjobs.com/pl/job/mid-senior-javascript-developer-codete-remote-0feydn35', 'frontend'),
               ('www.nofluffjobs.com/pl/job/ruby-on-rails-developer-useo-wroclaw-fbimv81n', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/powerbi-developer-prodata-consult-warsaw-tcon7jiu', 'gaming'),
               ('www.nofluffjobs.com/pl/job/java-developer-softserve-wroclaw-giwl7e7v', 'backend'),
               ('www.nofluffjobs.com/pl/job/remote-ux-ui-designer-expedite-commerce-vxrru1fe', 'ux'),
               ('www.nofluffjobs.com/pl/job/senior-ux-researcher-netguru-remote-pgvzvlrd', 'ux'),
               ('www.nofluffjobs.com/pl/job/software-engineer-zooplus-polska-krakow-i3gu2ct6', 'backend'),
               ('www.nofluffjobs.com/pl/job/senior-net-engineer-prodata-consult-wroclaw-0whvvknk', 'backend'),
               ('www.nofluffjobs.com/pl/job/embedded-software-programmer-randstad-wroclaw-fos7y6u3', 'embedded'),
               ('www.nofluffjobs.com/pl/job/java-developer-process-automation-link-group-warszawa-zuxeqcvl', 'backend'),
               ('www.nofluffjobs.com/pl/job/it-administrator-sharepoint-o365-optiveum-warsaw-f316fb4j',
                'it-administrator'),
               ('www.nofluffjobs.com/pl/job/flutter-developer-freelance-objectivity-remote-b6xzbfdl', 'mobile'),
               ('www.nofluffjobs.com/pl/job/python-developer-prodata-consult-warszawa-r50kv1zk', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/mlodszy-programista-java-dahliamatic-warszawa-ssbgwnxr', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/react-developer-prodata-consult-wroclaw-wrjuw1qr', 'frontend'),
               ('www.nofluffjobs.com/pl/job/net-developer-link-group-lodz-8d6rvpac', 'fullstack'), (
               'www.nofluffjobs.com/pl/job/infrastructure-virtualization-engineer-alois-staffing-krakow-fivkogz5',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/marketing-project-manager-placewise-krakow-8zpqrrx2', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/engineering-manager-codilime-warsaw-rkdebyyp', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/oracle-dba-prodata-consult-warsaw-rorinjwm', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/remote-ios-developer-vlogit-3w0j4dr9', 'mobile'),
               ('www.nofluffjobs.com/pl/job/c-developer-siili-szczecin-chwreu2w', 'gaming'), (
               'www.nofluffjobs.com/pl/job/senior-backend-developer-wyzsza-szkola-ksztalcenia-zawodowego-wroclaw-h0itkxjb',
               'backend'), (
               'www.nofluffjobs.com/pl/job/salesforce-technical-support-specialist-precursive-ltd-remote-ih02knut',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/c-c-developer-z-wave-futurehome-as-remote-6hga3los', 'embedded'), (
               'www.nofluffjobs.com/pl/job/administrator-linux-with-ansible-prodata-consult-warszawa-sghxbpq4',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/c-c-embedded-developer-neubloc-polska-remote-eqvmldhm', 'embedded'),
               ('www.nofluffjobs.com/pl/job/architekt-systemowy-prodata-consult-warszawa-kqrtscm3', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/senior-c-mfc-developer-integra-software-remote-ui35azgu', 'embedded'), (
               'www.nofluffjobs.com/pl/job/senior-information-security-specialist-smartrecruiters-krakow-rlgs7ike',
               'backoffice'),
               ('www.nofluffjobs.com/pl/job/senior-fullstack-net-developer-weegree-it-opole-mptgll8t', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/javascript-developer-link-group-warsaw-w3tbke1j', 'frontend'),
               ('www.nofluffjobs.com/pl/job/embedded-software-team-manager-polkomtel-warszawa-dl87eb7p', 'embedded'),
               ('www.nofluffjobs.com/pl/job/net-engineer-avenga-warsaw-zzerkc6k', 'backend'),
               ('www.nofluffjobs.com/pl/job/ui-designer-efigence-remote-jpkqiejg', 'ux'),
               ('www.nofluffjobs.com/pl/job/test-and-release-manager-avenga-wroclaw-euklxyv2', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/c-developer-siili-szczecin-chwreu2w', 'embedded'),
               ('www.nofluffjobs.com/pl/job/senior-big-data-engineer-softserve-remote-iogejfiw', 'big-data'),
               ('www.nofluffjobs.com/pl/job/senior-product-designer-poland-kahoot-remote-nj9szeat', 'gaming'),
               ('www.nofluffjobs.com/pl/job/embedded-software-engineer-hcc-embedded-kft-budapest-e6uif04c', 'embedded'),
               ('www.nofluffjobs.com/pl/job/mysql-developer-andersen-lab-krakow-e0rfprx8', 'big-data'), (
               'www.nofluffjobs.com/pl/job/system-administrator-solid-bridge-solutions-warszawa-fbtjwlp0',
               'it-administrator'), ('www.nofluffjobs.com/pl/job/ios-developer-euvic-remote-krss4qvg', 'mobile'),
               ('www.nofluffjobs.com/pl/job/linux-administrator-devops-vlog-remote-wedtwdbu', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/node-developer-prodata-consult-wroclaw-zibjmrs5', 'frontend'),
               ('www.nofluffjobs.com/pl/job/project-manager-clearcode-wroclaw-uqnhyt4c', 'project-manager'), (
               'www.nofluffjobs.com/pl/job/junior-technical-project-manager-ynd-technologies-remote-cynvl1yp',
               'project-manager'),
               ('www.nofluffjobs.com/pl/job/remote-ios-sdk-developer-grasza-consulting-xjezyycx', 'mobile'),
               ('www.nofluffjobs.com/pl/job/it-operations-engineer-recruitee-poznan-rzyr2xss', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/release-manager-generali-warszawa-tizy2q35', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/ios-technical-lead-unravel-remote-eem1boqb', 'mobile'),
               ('www.nofluffjobs.com/pl/job/backend-software-engineer-naviparking-gliwice-6xhvo3xi', 'backend'),
               ('www.nofluffjobs.com/pl/job/big-data-engineer-akamai-technologies-krakow-opr7jc69', 'big-data'),
               ('www.nofluffjobs.com/pl/job/embedded-software-engineer-nbc-zabierzow-jlmezwjm', 'embedded'),
               ('www.nofluffjobs.com/pl/job/data-engineer-unity-group-remote-ndxashlu', 'big-data'),
               ('www.nofluffjobs.com/pl/job/golang-engineer-smart-adserver-krakow-91pqrwwb', 'backend'),
               ('www.nofluffjobs.com/pl/job/embedded-c-software-engineer-semihalf-krakow-0ucyyctf', 'embedded'),
               ('www.nofluffjobs.com/pl/job/visual-designer-avanade-poland-krakow-5lkv4ydz', 'ux'), (
               'www.nofluffjobs.com/pl/job/digital-signal-processing-dsp-engineer-is-wireless-warszawapiaseczno-o2ss5zsk',
               'embedded'),
               ('www.nofluffjobs.com/pl/job/it-service-manager-prodata-consult-gdynia-w1ahrtrv', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/javascript-developer-avenga-remote-l2mfd8pl', 'frontend'), (
               'www.nofluffjobs.com/pl/job/senior-full-stack-developer-with-german-vm-pl-software-house-wroclaw-zbfredjv',
               'fullstack'),
               ('www.nofluffjobs.com/pl/job/requirements-engineer-devire-katowice-jhywwc0g', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/senior-frontend-developer-360-code-lab-warsaw-6pkorecn', 'frontend'),
               ('www.nofluffjobs.com/pl/job/android-developer-miquido-krakow-ji7gk0x2', 'mobile'),
               ('www.nofluffjobs.com/pl/job/ux-ui-designer-hl-tech-warsaw-g8dhirzb', 'ux'),
               ('www.nofluffjobs.com/pl/job/ecommerce-project-management-divante-remote-9ozpkobi', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/android-developer-do-ok-remote-qg5jmns3', 'mobile'), (
               'www.nofluffjobs.com/pl/job/iot-software-developer-haris-digital-engineering-kft-budapest-eyhexxwx',
               'embedded'), ('www.nofluffjobs.com/pl/job/it-administrator-global-primex-europe-warszawa-ewjq631d',
                             'it-administrator'), (
               'www.nofluffjobs.com/pl/job/senior-fullstack-developer-react-node-codibly-remote-fc6f97ho', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/c-c-embedded-developer-sii-polska-katowice-8xytwrpm', 'embedded'),
               ('www.nofluffjobs.com/pl/job/python-engineer-remote-ringier-axel-springer-polska-0p8jrcgl', 'backend'),
               ('www.nofluffjobs.com/pl/job/ios-developer-untitled-kingdom-krakow-mwgwdmkk', 'mobile'),
               ('www.nofluffjobs.com/pl/job/junior-net-developer-ecom-torun-suol5wbd', 'backend'),
               ('www.nofluffjobs.com/pl/job/android-developer-stava-opole-6ozjdlbg', 'mobile'),
               ('www.nofluffjobs.com/pl/job/frontend-developer-bridgemaker-tech-poznan-hbk4vkaq', 'frontend'),
               ('www.nofluffjobs.com/pl/job/senior-product-designer-poland-kahoot-remote-nj9szeat', 'ux'),
               ('www.nofluffjobs.com/pl/job/ios-developer-avenga-warszawa-67ee7n3v', 'mobile'), (
               'www.nofluffjobs.com/pl/job/virtualization-administrator-dahliamatic-krakow-ctgghjyf',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/react-native-developer-akanza-lublin-auhvfmlr', 'mobile'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-doit-software-gliwice-lushxbsc', 'gaming'),
               ('www.nofluffjobs.com/pl/job/test-automation-engineer-link-group-remote-9vgmxwjs', 'gaming'),
               ('www.nofluffjobs.com/pl/job/sys-admin-devops-webanywhere-katowice-voiysjyh', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/react-native-developer-escola-gdansk-zevfgjuj', 'mobile'),
               ('www.nofluffjobs.com/pl/job/fullstack-net-developer-sigma-it-polska-remote-srt8idk1', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/data-scientist-samba-tv-warszawa-raxc2ubf', 'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/remote-unity-game-developer-devire-mixhrd4b', 'gaming'),
               ('www.nofluffjobs.com/pl/job/frontend-developer-next-it-poznan-p2vzikfm', 'frontend'),
               ('www.nofluffjobs.com/pl/job/administrator-infrastruktury-britenet-remote-e1nxe87c', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/product-designer-fireart-studio-remote-laqu5f7j', 'ux'),
               ('www.nofluffjobs.com/pl/job/powerbi-developer-avenga-remote-fw97wvsm', 'big-data'),
               ('www.nofluffjobs.com/pl/job/java-developer-power-media-wroclaw-eymyaidk', 'backend'),
               ('www.nofluffjobs.com/pl/job/remote-fullstack-javascript-developer-tbba-b-v-rjryapql', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/data-engineer-spark-python-growbots-remote-gmhq4f9l', 'big-data'), (
               'www.nofluffjobs.com/pl/job/infrastructure-operations-specialist-prodata-consult-gdynia-skjnzmyn',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/junior-react-engineer-rumble-fish-poland-krakow-jqgetzal', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/angular-front-end-developer-optiveum-krakow-umq6b7ih', 'frontend'),
               ('www.nofluffjobs.com/pl/job/chatbot-developer-link-group-remote-chnbsomm', 'backoffice'), (
               'www.nofluffjobs.com/pl/job/data-scientist-internet-of-things-sigma-it-polska-wroclaw-cylxkv37',
               'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/android-developer-blockchain-avenga-warszawa-me8rcswi', 'mobile'),
               ('www.nofluffjobs.com/pl/job/javascript-devops-engineer-molecule-one-warszawa-uw4oqbos', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/ux-ui-designer-ynd-technologies-remote-0surixkn', 'ux'),
               ('www.nofluffjobs.com/pl/job/senior-mobile-react-native-developer-link-group-remote-rc1axfq9', 'mobile'),
               ('www.nofluffjobs.com/pl/job/trainee-junior-data-science-engineer-algopoli-ai-warszawa-4supmbvv',
                'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/jira-administrator-deviniti-remote-9dvxjpy4', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-edipresse-polska-warszawa-idpq9dw4', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/full-stack-net-developer-assemble-world-a-s-remote-sr3msvrf', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/chatbot-developer-link-group-remote-chnbsomm', 'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/remote-flutter-developer-link-group-7u3etbm0', 'mobile'),
               ('www.nofluffjobs.com/pl/job/senior-data-engineer-idemia-lodz-6g5hwaki', 'big-data'),
               ('www.nofluffjobs.com/pl/job/big-data-developer-itds-polska-remote-ttzndemf', 'big-data'),
               ('www.nofluffjobs.com/pl/job/it-recruiter-180-teamconnect-warszawa-cy36paal', 'backoffice'),
               ('www.nofluffjobs.com/pl/job/senior-devops-engineer-link-group-remote-z5skefbd', 'backoffice'),
               ('www.nofluffjobs.com/pl/job/big-data-developer-avenga-warsaw-tokxzaoz', 'big-data'),
               ('www.nofluffjobs.com/pl/job/engineering-manager-brainly-remote-njhtzz8a', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/linux-system-engineer-sorint-lab-frankfurt-htyg6gaj', 'it-administrator'), (
               'www.nofluffjobs.com/pl/job/inzynier-big-data-raiffeisen-bank-international-spolka-akcyjna-oddzial-w-polsce-warszawa-j9dixm3x',
               'big-data'), (
               'www.nofluffjobs.com/pl/job/administrator-hpc-cloud-storage-poznan-supercomputing-and-networking-center-poznan-jqjpr2ex',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/senior-ux-ui-designer-flyr-poland-krakow-tlarajqe', 'ux'),
               ('www.nofluffjobs.com/pl/job/python-web-developer-sigma-it-polska-remote-fyc0qvpo', 'backend'), (
               'www.nofluffjobs.com/pl/job/fullstack-blockchain-developer-rumble-fish-software-development-krakow-u0leqjej',
               'fullstack'),
               ('www.nofluffjobs.com/pl/job/cloud-transformation-consultant-avenga-warsaw-ucrnoime', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/analityk-hurtowni-danych-avenga-warszawa-ksrriuc5', 'big-data'), (
               'www.nofluffjobs.com/pl/job/fullstack-developer-angular-remote-motorola-solutions-o3ndbkht',
               'fullstack'), ('www.nofluffjobs.com/pl/job/senior-data-scientist-silent-eight-pte-ltd-remote-lylz60xw',
                              'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/remote-vue-js-developer-opstalent-oymwxyfr', 'frontend'),
               ('www.nofluffjobs.com/pl/job/embedded-software-engineer-polkomtel-warszawa-wbx1dukm', 'embedded'),
               ('www.nofluffjobs.com/pl/job/senior-software-engineer-frontend-displate-warsaw-m7oup1zz', 'frontend'),
               ('www.nofluffjobs.com/pl/job/remote-junior-data-engineer-python-dev-sidnet-0oohumgc', 'big-data'),
               ('www.nofluffjobs.com/pl/job/graphics-developer-artifex-mundi-katowice-cwuhjdb3', 'ux'),
               ('www.nofluffjobs.com/pl/job/modern-java-developer-codedose-cdx-remote-cc9qfltw', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/remote-big-data-developer-britenet-lafdfsyg', 'big-data'), (
               'www.nofluffjobs.com/pl/job/sql-database-administrator-prodata-consult-warsaw-hz57aotn',
               'it-administrator'), ('www.nofluffjobs.com/pl/job/games-web-apps-designer-iiit-remote-et6kyfzw', 'ux'),
               ('www.nofluffjobs.com/pl/job/senior-python-developer-360-code-lab-warsaw-co0xqite', 'backend'),
               ('www.nofluffjobs.com/pl/job/android-developer-valuelogic-remote-zxmrgwv3', 'mobile'),
               ('www.nofluffjobs.com/pl/job/data-engineer-data-architect-apreel-warszawa-yps7uzex', 'big-data'),
               ('www.nofluffjobs.com/pl/job/mid-senior-reactjs-developer-useo-remote-szvscxi2', 'frontend'),
               ('www.nofluffjobs.com/pl/job/service-delivery-manager-avenga-wroclaw-2vmgttsh', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/data-operation-nowcasting-ai-wroclaw-mub0qg8k', 'backoffice'),
               ('www.nofluffjobs.com/pl/job/big-data-engineer-softserve-remote-dba58y3t', 'big-data'),
               ('www.nofluffjobs.com/pl/job/it-administrator-finitec-sp-z-o-o-remote-paagelzz', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/senior-ios-developer-netguru-remote-rgp8i1iu', 'mobile'),
               ('www.nofluffjobs.com/pl/job/systems-engineer-scs-expert-warszawa-nsqjgfrh', 'it-administrator'), (
               'www.nofluffjobs.com/pl/job/programista-baz-danych-oracle-pl-sql-finitec-sp-z-o-o-remote-dozadqjm',
               'big-data'),
               ('www.nofluffjobs.com/pl/job/head-of-digital-link-group-warsaw-s27oqkjt', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/fullstack-developer-denstu-polska-remote-kl8derft', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/ux-ui-designer-avenga-remote-js4wke5q', 'ux'),
               ('www.nofluffjobs.com/pl/job/salesforce-administrator-link-group-remote-x8jvyevu', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/remote-flutter-developer-link-group-oypwwwmx', 'mobile'),
               ('www.nofluffjobs.com/pl/job/c-c-linux-kernel-developer-remote-neubloc-polska-mllipcrk', 'embedded'), (
               'www.nofluffjobs.com/pl/job/project-manager-officer-prodata-consult-warszawa-u3wlauio',
               'project-manager'),
               ('www.nofluffjobs.com/pl/job/remote-fullstack-developer-codete-9a5erw4y', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/android-developer-dahliamatic-warszawa-mkn2tjmo', 'mobile'), (
               'www.nofluffjobs.com/pl/job/technical-team-leader-net-python-js-ihs-markit-energy-gdansk-fn9s55f4',
               'fullstack'), (
               'www.nofluffjobs.com/pl/job/remote-data-network-engineer-general-dynamics-mission-systems-fvfav4mw',
               'it-administrator'), (
               'www.nofluffjobs.com/pl/job/senior-big-data-engineer-kafka-narwhal-data-solutions-remote-7d4dv4vn',
               'big-data'),
               ('www.nofluffjobs.com/pl/job/mlodszy-kierownik-projektow-vlogit-warszawa-dzbn8bzd', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/big-data-architect-softserve-remote-u3iocapw', 'big-data'),
               ('www.nofluffjobs.com/pl/job/rpa-developer-link-group-krakow-wdh4tat0', 'backend'),
               ('www.nofluffjobs.com/pl/job/mlops-machine-learning-engineer-getindata-remote-vbtujcp8', 'big-data'),
               ('www.nofluffjobs.com/pl/job/big-data-developer-aws-rite-nrg-remote-yoxmm3gm', 'big-data'),
               ('www.nofluffjobs.com/pl/job/c-embedded-developer-thaumatec-wroclaw-hsxpqd2g', 'embedded'),
               ('www.nofluffjobs.com/pl/job/lead-frontend-developer-crustlab-krakow-ujgtbmlt', 'frontend'),
               ('www.nofluffjobs.com/pl/job/game-developer-ten-square-games-wroclaw-8zoupypw', 'gaming'),
               ('www.nofluffjobs.com/pl/job/automation-engineer-devire-warsaw-xkpuuwbd', 'ux'),
               ('www.nofluffjobs.com/pl/job/senior-software-engineer-exida-warszawa-hxcoqo15', 'embedded'),
               ('www.nofluffjobs.com/pl/job/big-data-engineer-link-group-remote-g18st7sh', 'big-data'),
               ('www.nofluffjobs.com/pl/job/ux-ui-designer-perfect-gym-solutions-warszawa-yvxondxs', 'ux'),
               ('www.nofluffjobs.com/pl/job/senior-android-developer-link-group-krakow-t4mru1wx', 'mobile'),
               ('www.nofluffjobs.com/pl/job/senior-scala-developer-softwaremill-remote-19cfnggx', 'backend'),
               ('www.nofluffjobs.com/pl/job/data-engineer-netguru-remote-qxnizahf', 'big-data'), (
               'www.nofluffjobs.com/pl/job/it-and-technology-manager-prodata-consult-warszawa-8dfabi2v',
               'project-manager'),
               ('www.nofluffjobs.com/pl/job/scrum-master-prodata-consult-warszawa-thc5x0dj', 'gaming'),
               ('www.nofluffjobs.com/pl/job/macos-programmer-eset-krakow-1it5hboe', 'backend'), (
               'www.nofluffjobs.com/pl/job/fullstack-developer-aws-serverless-grasza-consulting-remote-1a58ucgz',
               'fullstack'), ('www.nofluffjobs.com/pl/job/remote-fullstack-developer-shortlist-ln9ldlh6', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/team-leader-magento-natura-warszawa-rjzckaec', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/backend-developer-bridgemaker-tech-poznan-qnxrjxp5', 'backend'),
               ('www.nofluffjobs.com/pl/job/full-stack-net-with-angular-solteq-poland-remote-rchfz1dd', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/net-developer-ework-group-remote-taipm86z', 'backend'), (
               'www.nofluffjobs.com/pl/job/system-administrator-bnp-paribas-solutions-warsaw-shi1tuvd',
               'it-administrator'), (
               'www.nofluffjobs.com/pl/job/machine-learning-engineer-global-app-testing-remote-hhvqyzr0',
               'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/senior-vue-js-developer-opstalent-remote-kvusinsk', 'frontend'), (
               'www.nofluffjobs.com/pl/job/data-engineer-ai-avanade-poland-krakow-09cuzbh6', 'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/product-designer-upacjenta-remote-zufcdazd', 'ux'), (
               'www.nofluffjobs.com/pl/job/senior-net-angular-developer-motorola-solutions-remote-jvwh6kme',
               'fullstack'), (
               'www.nofluffjobs.com/pl/job/tech-project-manager-wunderman-thompson-budapest-remote-cdksemi5',
               'project-manager'),
               ('www.nofluffjobs.com/pl/job/junior-unity-developer-huuuge-games-bydgoszcz-r5i1mtkl', 'gaming'),
               ('www.nofluffjobs.com/pl/job/embedded-developer-flight-software-n7-space-warszawa-wnzk9jiw', 'embedded'),
               ('www.nofluffjobs.com/pl/job/senior-net-developer-devire-warszawa-ybomrn75', 'backend'),
               ('www.nofluffjobs.com/pl/job/remote-senior-data-scientist-idego-group-9f6alanr', 'big-data'),
               ('www.nofluffjobs.com/pl/job/software-engineering-manager-tomtom-lodz-yaed881z', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/java-scala-developer-citi-service-center-warszawa-h0xvu573', 'backend'), (
               'www.nofluffjobs.com/pl/job/administrator-biztalk-aplikacje-krytyczne-warszawa-ij4qzgkx',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/fullstack-developer-next-it-poznan-pz3twwpx', 'frontend'),
               ('www.nofluffjobs.com/pl/job/frontend-developer-expondo-polska-sp-k-remote-dl0uol7x', 'frontend'),
               ('www.nofluffjobs.com/pl/job/ios-developer-plenti-remote-fpe7nrip', 'mobile'),
               ('www.nofluffjobs.com/pl/job/azure-data-engineer-capgemini-wroclaw-w6oppde1', 'big-data'),
               ('www.nofluffjobs.com/pl/job/remote-senior-java-c-game-developer-techtailor-k5mv3nhc', 'gaming'),
               ('www.nofluffjobs.com/pl/job/creative-graphic-designer-webanywhere-katowice-nynptnlh', 'ux'),
               ('www.nofluffjobs.com/pl/job/android-developer-rekrutacja-pracownikow-ac-krakow-kt5jprmg', 'mobile'),
               ('www.nofluffjobs.com/pl/job/senior-ux-ui-designer-britenet-remote-qrkukuu9', 'ux'), (
               'www.nofluffjobs.com/pl/job/programista-aplikacji-mobilnych-android-cyfrowy-polsat-warszawa-zyuphmbi',
               'mobile'), ('www.nofluffjobs.com/pl/job/ux-designer-sii-polska-warsaw-inlmwp7m', 'ux'),
               ('www.nofluffjobs.com/pl/job/fullstack-net-engineer-cornerstone-on-demand-krakow-ifpv9thg', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/c-software-engineer-mobica-limited-szczecin-3npupxkt', 'embedded'), (
               'www.nofluffjobs.com/pl/job/it-system-engineer-w-linux-link-group-wroclaw-5inij6z2', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/java-developer-fis-sst-remote-pqsxbggx', 'backend'), (
               'www.nofluffjobs.com/pl/job/ai-ml-project-leader-higo-sense-warsaw-fsaurdmv', 'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/administrator-baz-danych-aplikacje-krytyczne-warszawa-wvnocfxg',
                'it-administrator'),
               ('www.nofluffjobs.com/pl/job/grafik-i-ux-designer-odc-group-sp-k-warszawa-speeatak', 'ux'),
               ('www.nofluffjobs.com/pl/job/senior-ruby-engineer-link-group-krakow-wbxliade', 'backend'), (
               'www.nofluffjobs.com/pl/job/senior-machine-learning-architect-idego-group-remote-u309hmkb',
               'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/python-web-developer-netguru-remote-u83owek8', 'backend'),
               ('www.nofluffjobs.com/pl/job/product-designer-efigence-remote-0vnif1ie', 'ux'),
               ('www.nofluffjobs.com/pl/job/remote-golang-developer-link-group-ycgqzil0', 'backend'),
               ('www.nofluffjobs.com/pl/job/engineering-manager-pay-ship-olx-group-remote-219fmwf6', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/programista-c-apart-suchylas-veo8kukl', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/c-developer-huuuge-games-warszawa-qrgnjmyp', 'embedded'),
               ('www.nofluffjobs.com/pl/job/web-developer-redcompass-ltd-remote-tpfs1z92', 'frontend'),
               ('www.nofluffjobs.com/pl/job/ux-ui-designer-idemia-lodz-ijrwulnx', 'ux'),
               ('www.nofluffjobs.com/pl/job/c-developer-astek-polska-wroclaw-ywhxrlbw', 'embedded'),
               ('www.nofluffjobs.com/pl/job/frontend-developer-tbba-b-v-remote-i6piv1w5', 'frontend'),
               ('www.nofluffjobs.com/pl/job/senior-web-developer-gigaset-remote-lk97zqeb', 'frontend'),
               ('www.nofluffjobs.com/pl/job/remote-unity-game-developer-rage-quit-games-hku6bf2h', 'gaming'),
               ('www.nofluffjobs.com/pl/job/c-c-embedded-developer-link-group-krakow-s1zuetwk', 'embedded'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-piggy-llc-remote-ezqgp3t8', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/ux-designer-codibly-krakow-9vomtyeo', 'ux'),
               ('www.nofluffjobs.com/pl/job/project-lead-divante-remote-wn2mdwe2', 'backoffice'),
               ('www.nofluffjobs.com/pl/job/system-engineer-devire-katowice-bmyuyjs8', 'embedded'),
               ('www.nofluffjobs.com/pl/job/remote-scala-big-data-developer-mindbox-4ch84axz', 'big-data'),
               ('www.nofluffjobs.com/pl/job/team-leader-frontend-staples-solutions-gdansk-q9kg07qi', 'frontend'), (
               'www.nofluffjobs.com/pl/job/ios-developer-meetlify-spolka-z-ograniczona-odpowiedzialnoscia-katowice-u1paigzg',
               'mobile'), ('www.nofluffjobs.com/pl/job/fullstack-developer-beesafe-warszawa-t5nrgsjx', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/system-administrator-cloud-best-warszawa-gnzzlje8', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/automotive-project-lead-siili-szczecin-qggmijri', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/senior-angular-developer-cic-poland-warsaw-l0jijzr5', 'frontend'),
               ('www.nofluffjobs.com/pl/job/automotive-project-lead-siili-wroclaw-55suxb7u', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/senior-data-engineer-netguru-remote-foriw5qq', 'big-data'), (
               'www.nofluffjobs.com/pl/job/senior-data-scientist-mim-solutions-remote-5bhy6esa',
               'artificial-intelligence'), ('www.nofluffjobs.com/pl/job/ux-designer-netguru-remote-8ftj9fxb', 'ux'),
               ('www.nofluffjobs.com/pl/job/react-frontend-developer-tooploox-remote-u5brmffq', 'frontend'),
               ('www.nofluffjobs.com/pl/job/kernel-optimization-engineer-devire-remote-jbqiugem', 'embedded'),
               ('www.nofluffjobs.com/pl/job/salesforce-technical-architect-polsource-remote-rgpswd1e', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/engineering-manager-u2u-comms-olx-group-remote-r5e8fif8', 'backend'),
               ('www.nofluffjobs.com/pl/job/big-data-developer-sii-polska-warszawa-eozwfvst', 'big-data'), (
               'www.nofluffjobs.com/pl/job/mlodszy-programista-c-qualityassurance-phoenix-systems-lomza-cna5orbh',
               'embedded'), (
               'www.nofluffjobs.com/pl/job/junior-project-manager-alm-services-technology-group-remote-uv5qxdxd',
               'project-manager'),
               ('www.nofluffjobs.com/pl/job/frontend-developer-staples-solutions-gdansk-l5fnrcqo', 'frontend'), (
               'www.nofluffjobs.com/pl/job/data-scientist-computer-vision-deepsense-ai-remote-9fza3g0j',
               'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/senior-net-developer-with-xamarin-notime-wroclaw-fhxhordj', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/senior-big-data-engineer-devire-remote-pff3f9cp', 'big-data'),
               ('www.nofluffjobs.com/pl/job/programista-xamarin-aplikacje-krytyczne-warszawa-kto2fatb', 'mobile'), (
               'www.nofluffjobs.com/pl/job/kierownik-zespolu-front-end-aplikacje-krytyczne-warszawa-qkdtrgiz',
               'frontend'),
               ('www.nofluffjobs.com/pl/job/remote-data-engineer-python-developer-sidnet-fup03xvk', 'big-data'),
               ('www.nofluffjobs.com/pl/job/remote-android-developer-super-devs-au2nknjw', 'mobile'),
               ('www.nofluffjobs.com/pl/job/ux-ui-designer-freeport-metrics-warsaw-qwvdd555', 'ux'),
               ('www.nofluffjobs.com/pl/job/embedded-software-engineer-spyrosoft-krakow-1foa8fej', 'embedded'),
               ('www.nofluffjobs.com/pl/job/c-embedded-developer-pit-radwar-warszawa-my8sgjn6', 'embedded'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-unity-group-wroclaw-5ankim1s', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/web-game-developer-optimo-development-remote-ddhac1wj', 'frontend'),
               ('www.nofluffjobs.com/pl/job/senior-infrastructure-administrator-brainly-remote-zajobg0m', 'backoffice'),
               ('www.nofluffjobs.com/pl/job/senior-java-developer-higo-sense-remote-6j8dslp3', 'backend'),
               ('www.nofluffjobs.com/pl/job/it-administrator-tuatara-warszawa-nvsuyh9v', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/java-kotlin-developer-glantus-remote-d5ligpvz', 'backend'),
               ('www.nofluffjobs.com/pl/job/fullstack-javascript-developer-stermedia-remote-6izfg1fu', 'fullstack'), (
               'www.nofluffjobs.com/pl/job/python-software-engineer-kubernetes-deepsense-ai-warsaw-rvn69ifd',
               'artificial-intelligence'), (
               'www.nofluffjobs.com/pl/job/senior-it-project-manager-sdm-manager-winged-it-remote-mkrcslf7',
               'project-manager'), ('www.nofluffjobs.com/pl/job/c-game-developer-appliscale-remote-nihudh3d', 'gaming'),
               ('www.nofluffjobs.com/pl/job/frontend-developer-wyzsza-szkola-ksztalcenia-zawodowego-wroclaw-smz5f3da',
                'frontend'), ('www.nofluffjobs.com/pl/job/senior-unreal-technical-artist-siili-wroclaw-5wbpbjj3', 'ux'),
               ('www.nofluffjobs.com/pl/job/vue-js-developer-link-group-remote-tizq7qtu', 'frontend'),
               ('www.nofluffjobs.com/pl/job/junior-net-developer-x-deft-sp-k-bielskobiala-3exdb4qh', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/data-scientist-mim-solutions-remote-yur5xwbg', 'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/c-python-developer-iteo-katowice-dvy0s0l8', 'embedded'), (
               'www.nofluffjobs.com/pl/job/full-stack-net-developer-with-react-solteq-poland-remote-kldxfv3z',
               'fullstack'), (
               'www.nofluffjobs.com/pl/job/machine-learning-engineer-sport-algorithmics-and-gaming-sag-warsaw-fbeapp9y',
               'artificial-intelligence'), ('www.nofluffjobs.com/pl/job/ux-ui-designer-euvic-gliwice-sozeuqtp', 'ux'),
               ('www.nofluffjobs.com/pl/job/embedded-developer-siili-wroclaw-es9xrzea', 'embedded'), (
               'www.nofluffjobs.com/pl/job/software-engineer-mobile-developer-ios-smartpatient-business-services-warsaw-laaaebrz',
               'mobile'), ('www.nofluffjobs.com/pl/job/ux-ui-designer-devire-warszawa-jhkfy3i1', 'ux'), (
               'www.nofluffjobs.com/pl/job/senior-front-end-developer-with-german-vm-pl-software-house-wroclaw-qivfdokc',
               'frontend'), ('www.nofluffjobs.com/pl/job/senior-php-developer-360-code-lab-warsaw-lmdyqeh9', 'backend'),
               ('www.nofluffjobs.com/pl/job/project-manager-soltex-holding-poznan-w404uozr', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/regular-java-developer-link-group-krakow-ykj5b6oi', 'backend'),
               ('www.nofluffjobs.com/pl/job/junior-ux-ui-designer-helikon-tex-wroclaw-vrpjkbgj', 'ux'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-doit-software-gliwice-lushxbsc', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/data-analyst-fru-pl-krakow-06hpnqgm', 'big-data'),
               ('www.nofluffjobs.com/pl/job/hadoop-big-data-developer-avenga-gdansk-ltjpnwpn', 'big-data'),
               ('www.nofluffjobs.com/pl/job/fullstack-developer-buildit-warszawa-s7cvrtf6', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/mid-senior-unity-developer-mechanistry-remote-6m11vu6d', 'gaming'), (
               'www.nofluffjobs.com/pl/job/java-engineer-wannabe-cloud-engineer-motorola-solutions-krakow-uetbzbj9',
               'backend'),
               ('www.nofluffjobs.com/pl/job/cloud-engineer-cloudferro-warszawa-8oxgwgma', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/expert-software-engineer-tomtom-lodz-za2setvn', 'backend'),
               ('www.nofluffjobs.com/pl/job/android-ios-developer-survicate-remote-hfdjwujf', 'mobile'),
               ('www.nofluffjobs.com/pl/job/hadoop-administrator-onwelo-remote-kfkfp3ct', 'big-data'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-mirumee-software-wroclaw-hx1xduxt', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/unreal-engine-4-game-developer-image-powr-warszawa-gyefd6xu', 'gaming'),
               ('www.nofluffjobs.com/pl/job/big-data-developer-link-group-krakow-vzvpaijo', 'big-data'),
               ('www.nofluffjobs.com/pl/job/embedded-testing-engineer-devire-katowice-fpqwnvsn', 'embedded'),
               ('www.nofluffjobs.com/pl/job/project-lead-divante-remote-wn2mdwe2', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/scrum-master-sii-warsaw-cbhokicw', 'project-manager'), (
               'www.nofluffjobs.com/pl/job/senior-big-data-engineer-solid-bridge-solutions-warszawa-kt67d1ru',
               'big-data'), (
               'www.nofluffjobs.com/pl/job/programista-aplikacji-mobilnych-ios-cyfrowy-polsat-warszawa-zmtrdk1y',
               'mobile'), ('www.nofluffjobs.com/pl/job/java-developer-team-leader-10clouds-remote-vtik6qcp', 'backend'),
               ('www.nofluffjobs.com/pl/job/ui-ux-designer-forward-thinking-systems-polska-krakow-pyqdeuq7', 'ux'),
               ('www.nofluffjobs.com/pl/job/swift-software-engineer-ii-jamf-remote-rw2yau9z', 'mobile'), (
               'www.nofluffjobs.com/pl/job/ai-data-engineer-with-scala-lingaro-warsaw-hznc7gpi',
               'artificial-intelligence'), (
               'www.nofluffjobs.com/pl/job/senior-data-scientist-machine-learning-mieszkanie-pl-warszawa-acaiwvls',
               'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/embedded-developer-mobica-limited-szczecin-cauaixu0', 'embedded'),
               ('www.nofluffjobs.com/pl/job/it-administrator-ims-r-d-krakow-zcoyng2v', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/ui-ux-designer-plentific-remote-fqasmpym', 'ux'), (
               'www.nofluffjobs.com/pl/job/fullstack-developer-java-angular-idemia-poland-r-d-lodz-0j9q5tbe',
               'fullstack'), (
               'www.nofluffjobs.com/pl/job/specjalista-sap-basis-innogy-polska-it-support-warszawa-axgfoozc',
               'it-administrator'), ('www.nofluffjobs.com/pl/job/automation-engineer-devire-gdynia-ghki0jmx', 'ux'), (
               'www.nofluffjobs.com/pl/job/jira-sd-implementation-specialist-people-trust-remote-0tsptfgz',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/mdm-administrator-link-group-krakow-mdquzbb8', 'it-administrator'),
               ('www.nofluffjobs.com/pl/job/hr-specialist-perfect-gym-solutions-warszawa-cxvfrj0j', 'backoffice'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-prodata-consult-warsaw-y89jcxmw', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/fullstack-java-engineer-prodata-consult-remote-iuf7f9m4', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/ms-sql-database-architect-prodata-consult-warszawa-zb1mvoou', 'ux'), (
               'www.nofluffjobs.com/pl/job/mid-software-engineer-respo-vision-warszawa-xmpjus46',
               'artificial-intelligence'), (
               'www.nofluffjobs.com/pl/job/data-scientist-nlp-halobotics-warszawa-jtdcdbie', 'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/ui-designer-codibly-krakow-vuypntfi', 'ux'),
               ('www.nofluffjobs.com/pl/job/senior-ux-ui-designer-growbots-warszawa-gyl9em3g', 'ux'),
               ('www.nofluffjobs.com/pl/job/it-project-manager-pagepro-bialystok-qzskffht', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/net-sql-engineer-sigma-it-polska-remote-zqfdjohy', 'backend'),
               ('www.nofluffjobs.com/pl/job/senior-digital-architect-alcon-warszawa-6fqkhy4r', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/remote-android-sdk-developer-grasza-consulting-x7ex1uol', 'mobile'), (
               'www.nofluffjobs.com/pl/job/technical-project-manager-wunderman-thompson-technology-poznan-1pywls0j',
               'project-manager'), (
               'www.nofluffjobs.com/pl/job/front-end-developer-angular-motorola-solutions-remote-sh3isdem', 'frontend'),
               ('www.nofluffjobs.com/pl/job/mlodszy-specjalista-ds-data-center-prodata-consult-warszawa-ur2pba54',
                'it-administrator'), ('www.nofluffjobs.com/pl/job/ios-developer-kingit-remote-4twollsb', 'mobile'),
               ('www.nofluffjobs.com/pl/job/embedded-systems-developer-lpn-plant-gdansk-mztnsitw', 'embedded'), (
               'www.nofluffjobs.com/pl/job/machine-learning-platform-architect-greensteam-warszawa-k3hpzemd',
               'artificial-intelligence'), (
               'www.nofluffjobs.com/pl/job/sap-business-training-coordinator-opel-manufacturing-poland-sp-o-o-gliwice-xxrhv3my',
               'backoffice'),
               ('www.nofluffjobs.com/pl/job/frontend-developer-optimo-development-remote-5hfbaucn', 'frontend'),
               ('www.nofluffjobs.com/pl/job/chatbot-developer-link-group-remote-fwr3tmw0', 'artificial-intelligence'), (
               'www.nofluffjobs.com/pl/job/computer-vision-researcher-respo-vision-warszawa-qmrk4rkn',
               'artificial-intelligence'),
               ('www.nofluffjobs.com/pl/job/fullstack-java-developer-kaft-remote-naetvz9x', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/senior-react-js-developer-codete-krakow-0yasocnj', 'frontend'),
               ('www.nofluffjobs.com/pl/job/senior-mobile-flutter-developer-deviniti-remote-augxketw', 'mobile'),
               ('www.nofluffjobs.com/pl/job/remote-ruby-on-rails-engineer-intratel-5kwncxdh', 'backend'), (
               'www.nofluffjobs.com/pl/job/senior-fullstack-developer-react-node-from-poland-with-dev-remote-ocatxuea',
               'fullstack'), (
               'www.nofluffjobs.com/pl/job/tech-lead-senior-java-developer-prodata-consult-warszawa-bio873hc',
               'fullstack'),
               ('www.nofluffjobs.com/pl/job/big-data-developer-stepstone-services-warszawa-y6xdjwkv', 'big-data'),
               ('www.nofluffjobs.com/pl/job/senior-product-designer-ux-ui-tonik-remote-fpjpjmcj', 'ux'),
               ('www.nofluffjobs.com/pl/job/ios-developer-miquido-krakow-d1vfllnc', 'mobile'),
               ('www.nofluffjobs.com/pl/job/java-solution-architect-link-group-warszawa-r1e8cfpz', 'backend'), (
               'www.nofluffjobs.com/pl/job/machine-learning-engineer-grape-up-krakow-v3za48gq',
               'artificial-intelligence'), (
               'www.nofluffjobs.com/pl/job/sql-server-database-administration-ework-group-remote-lfqvfdlk',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/frontend-developer-miquido-krakow-wldbtxh6', 'frontend'),
               ('www.nofluffjobs.com/pl/job/react-developer-sharespace-warsaw-5f9jyj1d', 'frontend'), (
               'www.nofluffjobs.com/pl/job/fullstack-developer-meetlify-spolka-z-ograniczona-odpowiedzialnoscia-katowice-6ua0wcvx',
               'fullstack'),
               ('www.nofluffjobs.com/pl/job/agile-project-lead-siili-wroclaw-5gam4jnu', 'project-manager'),
               ('www.nofluffjobs.com/pl/job/data-scientist-nowcasting-ai-wroclaw-awvnftyg', 'big-data'),
               ('www.nofluffjobs.com/pl/job/android-developer-snow-dog-poznan-wa55l4ej', 'mobile'), (
               'www.nofluffjobs.com/pl/job/specjalista-ds-konfiguracji-atlassian-ework-group-warsaw-pu0yfilp',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/senior-web-designer-poland-kahoot-remote-phy6gobx', 'ux'), (
               'www.nofluffjobs.com/pl/job/staff-software-engineer-mobile-android-cybersource-poznan-piigtyci',
               'mobile'),
               ('www.nofluffjobs.com/pl/job/remote-asp-net-developer-kinetix-trading-solutions-nbpkarbr', 'fullstack'),
               ('www.nofluffjobs.com/pl/job/ux-ui-designer-avsystem-krakow-i62xwbcm', 'ux'), (
               'www.nofluffjobs.com/pl/job/data-architect-data-modeler-direct-communication-remote-tzd9njfq',
               'big-data'),
               ('www.nofluffjobs.com/pl/job/senior-software-engineer-net-adform-warszawa-a1da1cof', 'backend'), (
               'www.nofluffjobs.com/pl/job/programista-swift-ios-poznan-supercomputing-and-networking-center-poznan-voiw62u4',
               'mobile'), (
               'www.nofluffjobs.com/pl/job/qt-software-developer-integrated-computer-solutions-remote-jyizu26j',
               'embedded'), ('www.nofluffjobs.com/pl/job/ux-ui-designer-greensteam-warszawa-sy2a3zvb', 'ux'),
               ('www.nofluffjobs.com/pl/job/senior-ios-engineer-happn-katowice-fjfkvwxh', 'mobile'),
               ('www.nofluffjobs.com/pl/job/react-native-developer-tooploox-remote-mwzttuii', 'frontend'),
               ('www.nofluffjobs.com/pl/job/senior-frontend-developer-avenga-remote-d4nnpe1w', 'frontend'), (
               'www.nofluffjobs.com/pl/job/infrastructure-azure-backup-admin-sudzucker-polska-wroclaw-0pzbopzz',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/frontend-tech-lead-codete-wroclaw-c2nbdrye', 'frontend'), (
               'www.nofluffjobs.com/pl/job/senior-mobile-react-native-developer-link-group-remote-rc1axfq9',
               'backoffice'),
               ('www.nofluffjobs.com/pl/job/mid-senior-net-core-developer-cshark-remote-fyhxqh81', 'backend'),
               ('www.nofluffjobs.com/pl/job/senior-software-engineer-front-end-ad-brainly-remote-krbxqwfr', 'frontend'),
               ('www.nofluffjobs.com/pl/job/product-designer-netguru-remote-2kabb3pr', 'ux'),
               ('www.nofluffjobs.com/pl/job/junior-embedded-systems-developer-lpn-plant-gdansk-clbokhli', 'embedded'), (
               'www.nofluffjobs.com/pl/job/infrastructure-wvd-administator-sudzucker-polska-wroclaw-eqzqufjh',
               'it-administrator'),
               ('www.nofluffjobs.com/pl/job/programista-front-end-aplikacje-krytyczne-warszawa-bryzobjc', 'frontend'),
               ('www.nofluffjobs.com/pl/job/cloud-data-engineer-ihs-markit-maritime-trade-remote-6cpcvkuo', 'big-data'),
               ('www.nofluffjobs.com/pl/job/remote-php-developer-stowarzyszenie-wiosna-h3lupoac', 'backend'),
               ('www.nofluffjobs.com/pl/job/system-administrator-binarapps-lodz-1u2c6nsq', 'it-administrator'), (
               'www.nofluffjobs.com/pl/job/starszy-programista-front-end-aplikacje-krytyczne-warszawa-bg4fqaji',
               'frontend'), (
               'www.nofluffjobs.com/pl/job/python-developer-data-scientist-affinda-pty-ltd-remote-cabth6hs',
               'artificial-intelligence'), (
               'www.nofluffjobs.com/pl/job/backend-developer-wyzsza-szkola-ksztalcenia-zawodowego-wroclaw-ifblyufd',
               'backend')]
